TARGET     = 
MODE       = bin
STACKSIZE  = 64k
MALLOCSIZE = 256k
MMAREA     = 0
OBJS       = $(TARGET).obj

INCPATH    = ../z_tools/guigui00/
CC1OPT     =
BIMOPT0    = -v48a
BIMOPT1    = -tek5 clv:5 eopt: eprm:

ARCFLIES   =
ARCORG     =
ARCTEK     =
BIMOPT2    =

include ../z_tools/com_mak.txt

# OBJS‚ğ‘‚«Š·‚¦‚é‚Æ•ªŠ„ƒRƒ“ƒpƒCƒ‹‘Î‰

# tolset08‘Î‰Makefile
